package: com.PigeonGames.Phigros  # phigros的包名
adb: adb\\adb.exe  # adb程序在PhigrosLocal文件夹下的相对路径
java: jdk-11.0.22\\bin\\java.exe  # java11(jdk11)在PhigrosLocal文件夹下的相对路径(如果jdk版本更新了则需要修改)
abe: abe.jar  # abe工具在PhigrosLocal文件夹下的相对路径
save: apps/com.PigeonGames.Phigros/sp/com.PigeonGames.Phigros.v2.playerprefs.xml  # 存档在解包后压缩包中的路径(就是在phigros.tar中的路径)
userdata_name: .userdata
outpath: ./  # 输出保存文件路径(运行脚本的相对路径，不是在PhigrosLocal文件夹下的相对路径)
check_file: True  # 是否启用环境检查(可以关可以不关)
check: # 环境检查的文件列表(不完整)
  adb_file: [ adb.exe,AdbWinApi.dll,AdbWinUsbApi.dll ]  # adb的仨文件(有且仅有仨文件是必要的)
  java_file: [ java.exe,java.dll,jar.exe ]  # java环境的关键文件(应该吧？)
  java_folder: [ bin,lib,jmods ]  # java环境的关键文件夹(应该吧？)